apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tileserver

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: tileserver-config
    files:
      - config.json
      - styles.json
