apiVersion: apps/v1
kind: Deployment
metadata:
  name: stac-browser
  namespace: odc-stac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stac-browser
  template:
    metadata:
      labels:
        app: stac-browser
    spec:
      containers:
        - name: stac-browser
          image: ghcr.io/radiantearth/stac-browser:4.0.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "0.25"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SB_catalogUrl
              value: "https://stac-api.staging.piksel.big.go.id"
---
apiVersion: v1
kind: Service
metadata:
  name: stac-browser
  namespace: odc-stac
spec:
  selector:
    app: stac-browser
  ports:
    - port: 80
      targetPort: 80
      name: http
