apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-public-data
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-public-readonly
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-coastline-data
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-coastline-rw
  resources:
    requests:
      storage: 1Gi
