apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terria

resources:
  - configmap-basemaps.yaml
  - deployment.yaml
  - service.yaml
  - hpa-pdb.yaml

configMapGenerator:
  - name: terria-client-config
    options:
      labels:
        app: terria
    files:
      - config.json
      - simple.json
  - name: terria-server-config
    options:
      labels:
        app: terria
    files:
      - serverconfig.json
